version: '3.8'

services:
  postgres:
    image: postgres:17.2
    container_name: test-docker
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: hafiz.127
      POSTGRES_DB: hotel_management # Specify your database name if needed
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    image: postgres # Replace with the actual image of your app (e.g., spring-boot-app)
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hotel_management # Use your actual DB name
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: hafiz.127
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:


